//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_management.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoIncrementRoomId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string autoIncrementRoomId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoIncrementRoomId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> autoIncrementRoomIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addRoomDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addRoomDetails(string id, string name, string description, string price, string country, string city, string package);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addRoomDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addRoomDetailsAsync(string id, string name, string description, string price, string country, string city, string package);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerHotel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string registerHotel(string name, string description, string location, string number, string sigupPass, string signupCPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registerHotel", ReplyAction="*")]
        System.Threading.Tasks.Task<string> registerHotelAsync(string name, string description, string location, string number, string sigupPass, string signupCPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchRoom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchRoom(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchRoomAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateRoom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool updateRoom(string id, string name, string desc, string price, string country, string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> updateRoomAsync(string id, string name, string desc, string price, string country, string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FindRoomCountry(string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FindRoomCountryAsync(string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FindRoomCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomCity", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FindRoomCityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FindRoomName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRoomName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FindRoomNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Hotel_management.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Hotel_management.ServiceReference1.WebService1Soap>, Hotel_management.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string autoIncrementRoomId() {
            return base.Channel.autoIncrementRoomId();
        }
        
        public System.Threading.Tasks.Task<string> autoIncrementRoomIdAsync() {
            return base.Channel.autoIncrementRoomIdAsync();
        }
        
        public string addRoomDetails(string id, string name, string description, string price, string country, string city, string package) {
            return base.Channel.addRoomDetails(id, name, description, price, country, city, package);
        }
        
        public System.Threading.Tasks.Task<string> addRoomDetailsAsync(string id, string name, string description, string price, string country, string city, string package) {
            return base.Channel.addRoomDetailsAsync(id, name, description, price, country, city, package);
        }
        
        public string registerHotel(string name, string description, string location, string number, string sigupPass, string signupCPass) {
            return base.Channel.registerHotel(name, description, location, number, sigupPass, signupCPass);
        }
        
        public System.Threading.Tasks.Task<string> registerHotelAsync(string name, string description, string location, string number, string sigupPass, string signupCPass) {
            return base.Channel.registerHotelAsync(name, description, location, number, sigupPass, signupCPass);
        }
        
        public System.Data.DataSet SearchRoom(string id) {
            return base.Channel.SearchRoom(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchRoomAsync(string id) {
            return base.Channel.SearchRoomAsync(id);
        }
        
        public bool updateRoom(string id, string name, string desc, string price, string country, string city) {
            return base.Channel.updateRoom(id, name, desc, price, country, city);
        }
        
        public System.Threading.Tasks.Task<bool> updateRoomAsync(string id, string name, string desc, string price, string country, string city) {
            return base.Channel.updateRoomAsync(id, name, desc, price, country, city);
        }
        
        public System.Data.DataSet FindRoomCountry(string country) {
            return base.Channel.FindRoomCountry(country);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FindRoomCountryAsync(string country) {
            return base.Channel.FindRoomCountryAsync(country);
        }
        
        public System.Data.DataSet FindRoomCity(string city) {
            return base.Channel.FindRoomCity(city);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FindRoomCityAsync(string city) {
            return base.Channel.FindRoomCityAsync(city);
        }
        
        public System.Data.DataSet FindRoomName(string name) {
            return base.Channel.FindRoomName(name);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FindRoomNameAsync(string name) {
            return base.Channel.FindRoomNameAsync(name);
        }
    }
}
